[package]
name = "minspan"
version = "0.1.3"
edition = "2018"
description = "a package for determining the minimum span of one vector within another"
license = "MIT"
repository = "https://github.com/mwotton/minspan"

[dependencies]

[dev-dependencies]
proptest = "1.6"
